services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  nui:
    image: ghcr.io/nats-nui/nui:latest
    ports:
      - "31311:31311"
    volumes:
      - ./data/nui_db:/db
    depends_on:
      - nats